-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

DROP TABLE IF EXISTS public.addresses CASCADE;
DROP TABLE IF EXISTS public.accounts CASCADE;
DROP TABLE IF EXISTS public.cities CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.postal_code CASCADE;
DROP TABLE IF EXISTS public.materials CASCADE;
DROP TABLE IF EXISTS public.material_variants CASCADE;
DROP TABLE IF EXISTS public.orders_material_variants CASCADE;

CREATE TABLE IF NOT EXISTS public.accounts
(
    account_id serial NOT NULL,
    role character varying(11) NOT NULL,
    username character varying(64) NOT NULL,
    password character varying(100),
    telephone integer,
    addresses_id integer NOT NULL,
    CONSTRAINT account_pk PRIMARY KEY (account_id)
);

CREATE TABLE IF NOT EXISTS public.addresses
(
    addresses_id serial NOT NULL,
    address character varying(64) NOT NULL,
    postal_code_id integer NOT NULL,
    city_id integer NOT NULL,
    CONSTRAINT addresses_pkey PRIMARY KEY (addresses_id)
);

CREATE TABLE IF NOT EXISTS public.cities
(
    city_id serial NOT NULL,
    city character varying(50) NOT NULL,
    CONSTRAINT cities_pkey PRIMARY KEY (city_id)
);

CREATE TABLE IF NOT EXISTS public.material_variants
(
    material_variant_id serial NOT NULL,
    length integer,
    height integer,
    width integer,
    material_id integer NOT NULL,
    CONSTRAINT material_variant_pk PRIMARY KEY (material_variant_id)
);

CREATE TABLE IF NOT EXISTS public.materials
(
    material_id serial NOT NULL,
    name character varying(100) NOT NULL,
    unit character varying(10) NOT NULL,
    price integer NOT NULL,
    order_id integer NOT NULL,
    CONSTRAINT material_pk PRIMARY KEY (material_id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    order_id serial NOT NULL,
    customer_id integer NOT NULL,
    carport_id integer NOT NULL,
    salesperson_id integer NOT NULL,
    status character varying(10) NOT NULL,
    price integer,
    order_placed timestamp with time zone,
    order_paid boolean NOT NULL,
    height integer NOT NULL,
    width integer NOT NULL,
    "hasShed" boolean,
    roof_type character varying(6) NOT NULL,
    account_id integer NOT NULL,
    m_id integer NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.orders_material_variants
(
    orders_order_id serial NOT NULL,
    material_variants_material_variant_id serial NOT NULL,
    quantity int,
    description character varying(100)
);

CREATE TABLE IF NOT EXISTS public.postal_code
(
    postal_code_id serial NOT NULL,
    postal_code integer NOT NULL,
    CONSTRAINT postal_code_pkey PRIMARY KEY (postal_code_id)
);

ALTER TABLE IF EXISTS public.accounts
    ADD CONSTRAINT addresses_fk FOREIGN KEY (addresses_id)
        REFERENCES public.addresses (addresses_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.addresses
    ADD CONSTRAINT city_fk FOREIGN KEY (city_id)
        REFERENCES public.cities (city_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.addresses
    ADD CONSTRAINT postal_code_fk FOREIGN KEY (postal_code_id)
        REFERENCES public.postal_code (postal_code_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.material_variants
    ADD CONSTRAINT fk FOREIGN KEY (material_id)
        REFERENCES public.materials (material_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT account_id_fk FOREIGN KEY (account_id)
        REFERENCES public.accounts (account_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.orders_material_variants
    ADD CONSTRAINT orders_material_variants_material_variants_material_varian_fkey FOREIGN KEY (material_variants_material_variant_id)
        REFERENCES public.material_variants (material_variant_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.orders_material_variants
    ADD CONSTRAINT orders_material_variants_orders_order_id_fkey FOREIGN KEY (orders_order_id)
        REFERENCES public.orders (order_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;

-- Insert materials into `materials`
INSERT INTO public.materials (name, unit, price, order_id)
VALUES
    ('25x200 mm. trykimp. Brædt', 'Stk', 0, 1),
    ('25x125mm. trykimp. Brædt', 'Stk', 0, 1),
    ('38x73 mm. Lægte ubh.', 'Stk', 0, 1),
    ('45x95 mm. Reglar ub.', 'Stk', 0, 1),
    ('45x195 mm. spærtræ ubh.', 'Stk', 0, 1),
    ('97x97 mm. trykimp. Stolpe', 'Stk', 0, 1),
    ('19x100 mm. trykimp. Brædt', 'Stk', 0, 1),
    ('Plastmo Ecolite blåtonet', 'Stk', 0, 1),
    ('plastmo bundskruer', 'Pakke', 0, 1),
    ('hulbånd 1x20 mm.', 'Rulle', 0, 1),
    ('universal 190 mm højre', 'Stk', 0, 1),
    ('universal 190 mm venstre', 'Stk', 0, 1),
    ('4,5 x 60 mm. skruer', 'Pakke', 0, 1),
    ('4,0 x 50 mm. beslagskruer', 'Pakke', 0, 1),
    ('bræddebolt 10 x 120 mm.', 'Stk', 0, 1),
    ('firkantskiver 40x40x11mm', 'Stk', 0, 1),
    ('4,5 x 70 mm. Skruer', 'Pakke', 0, 1),
    ('4,5 x 50 mm. Skruer', 'Pakke', 0, 1),
    ('stalddørsgreb 50x75', 'Sæt', 0, 1),
    ('t hængsel 390 mm', 'Stk', 0, 1),
    ('vinkelbeslag 35', 'Stk', 0, 1);

-- Insert material variants into `material_variants`
INSERT INTO public.material_variants (length, height, width, material_id)
VALUES
    (360, NULL, NULL, 1),
    (540, NULL, NULL, 1),
    (360, NULL, NULL, 2),
    (540, NULL, NULL, 2),
    (420, NULL, NULL, 3),
    (270, NULL, NULL, 4),
    (240, NULL, NULL, 4),
    (600, NULL, NULL, 5),
    (480, NULL, NULL, 5),
    (300, NULL, NULL, 6),
    (210, NULL, NULL, 7),
    (540, NULL, NULL, 7),
    (360, NULL, NULL, 7),
    (600, NULL, NULL, 8),
    (360, NULL, NULL, 8),
    (NULL, NULL, NULL, 9),
    (NULL, NULL, NULL, 10),
    (NULL, NULL, NULL, 11),
    (NULL, NULL, NULL, 12),
    (NULL, NULL, NULL, 13),
    (NULL, NULL, NULL, 14),
    (NULL, NULL, NULL, 15),
    (NULL, NULL, NULL, 16),
    (NULL, NULL, NULL, 17),
    (NULL, NULL, NULL, 18),
    (NULL, NULL, NULL, 19),
    (NULL, NULL, NULL, 20),
    (NULL, NULL, NULL, 21);

-- Insert into `orders_material_variants`
INSERT INTO public.orders_material_variants (orders_order_id, material_variants_material_variant_id, quantity, description)
VALUES
    (1, 1, 4, 'understernbrædder til for & bag ende'),
    (1, 2, 4, 'understernbrædder til siderne'),
    (1, 3, 2, 'oversternbrædder til forenden'),
    (1, 4, 4, 'oversternbrædder til siderne'),
    (1, 5, 1, 'z på bagside af dør'),
    (1, 6, 12, 'løsholter til skur gavle'),
    (1, 7, 4, 'løsholter til skur sider'),
    (1, 8, 15, 'spær, monteres på rem'),
    (1, 9, 2, 'remme i sider'),
    (1, 10, 11, 'stolper nedgraves 90 cm i jord'),
    (1, 11, 200, 'beklædning af skur 1 på 2'),
    (1, 12, 4, 'vandbrædt på stern i sider'),
    (1, 13, 2, 'vandbrædt på stern i forende'),
    (1, 14, 6, 'tagplader monteres på spær'),
    (1, 15, 6, 'tagplader monteres på spær'),
    (1, 16, 3, 'skruer til tagplader'),
    (1, 17, 2, 'vindkryds på spær'),
    (1, 18, 15, 'montering af spær på rem'),
    (1, 19, 15, 'montering af spær på rem'),
    (1, 20, 1, 'montering af stern og vandbrædt'),
    (1, 21, 3, 'montering af universalbeslag'),
    (1, 22, 18, 'montering af rem på stolper'),
    (1, 23, 12, 'montering af rem på stolper'),
    (1, 24, 2, 'yderste beklædning'),
    (1, 25, 2, 'inderste beklædning'),
    (1, 26, 1, 'lås på dør i skur'),
    (1, 27, 2, 'skurdør'),
    (1, 28, 32, 'montering af løsholter i skur');

END;