@startuml

|Kunde|
start
:Opret forespørgsel;

|Webshop|
:Forespørgsel oprettes;
:Kundeinfo oprettes i db;

|Sælger|
if (Pristilbud åbnes af sælger) then (afvist)
  :Pris i tilbud ændres;
  stop
else (Godkendes)
  :Bekræftelse på bestilling;
endif

|Webshop|

|Sælger|

|Lager|
:Lager sender faktura til kd;

stop
@enduml
