@startuml
'https://plantuml.com/activity-diagram-beta

|Kunde|
start
:Opret forespørgsmål;

|Webshop |
:Beregner pris og sender prisoverslag;

|Kunde|
if (Pristilbud godkendes) then (Nej)
  :Ingen stykliste og app stopper;
  stop
else (Ja)
  :Bekræftelse på bestilling;
endif

|Kunde|
:Betal;

|Webshop |
:Genererer stykliste;

|Kunde|
:Modtager stykliste + svg-tegning;

|Webshop |
:Sender plukliste til lager;
:Sender materiale til kunde;


|Kunde|
:Modtager materiale;

stop
@enduml