@startuml
'https://plantuml.com/sequence-diagram

skinparam backgroundColor #FEFEFE

actor Kunde
participant View as V
participant "OrderController.createQuery()" as C
participant "OrderMapper.createOrderInDb()" as M
participant DB


Kunde -> V: Kunde har udfyldt formularen

V -> C:

deactivate V

@enduml