@startuml
'https://plantuml.com/sequence-diagram

autonumber

Actor Kunde
participant View as V
participant Controller as C
participant Mapper as M
participant DB


Kunde -> V: Kd har udfyldt formularen og oprettet en forespørgsel
Kunde -> V: /createquery ruten tager imod height/width
V -> V: Input valideres i formen
activate V
V -> C: POST request til /createquery
activate C
C -> C: Beregner materialer (length + quantity)
C -> M: Kaster (length + quantity) til mapperen
activate M
M -> DB: eksekverer SQL
DB -> M: returnerer materiale
M -> C: returnerer material styklisten
M -> C: kaster db-exception
deactivate M
C -> C: griber sql-exception
C -> V: Renderer "materialelist.html"

deactivate V
@enduml