@startuml
'https://plantuml.com/sequence-diagram

autonumber

Ansat -> Intranet: Tilgår intranettet
Intranet -> Ansat: Viser dropdown-menu (administrator eller sælger)
Ansat -> Intranet: Vælger rolle (administrator eller sælger)
Intranet -> Database: Opdaterer session med valgt rolle
Database -> Intranet: Bekræftelse på opdatering
Intranet -> Ansat: Bekræftelse på valgt rolle og adgang til relevant sektion
@enduml