@startuml
'https://plantuml.com/sequence-diagram

autonumber

Sælger -> Webshop: Log ind
Sælger -> Webshop: Vælg en kundes forespørgsel
Webshop -> Database: Hent forespørgsel (carport detaljer, email, navn)
Database -> Webshop: Returner forespørgsel
Webshop -> Sælger: Vis forespørgsel (carport detaljer, navn og email)
Sælger -> Webshop: Tjek om forespørgsel kan godkendes
Sælger -> Webshop: Udfyld og send pristilbud
Webshop -> Database: Gem pristilbud
Database -> Webshop: Bekræft at pristilbud er gemt
Webshop -> Sælger: Bekræftelse på sendt pristilbud
@enduml