@startuml
'https://plantuml.com/sequence-diagram

autonumber

Sælger -> Webshop: Log ind
Webshop -> Sælger: Bekræfter log ind
Sælger -> Webshop: Vælg en kundes forespørgsel
Webshop -> Database: Hent forespørgsel (carport detaljer, email, navn)
Database -> Webshop: Returner forespørgsel
Webshop -> Sælger: Vis forespørgsel (carport detaljer, navn og email)
Sælger -> Webshop: Klikker på rediger forespørgsel
Webshop -> Sælger: Viser nuværende oplysninger i redigerings format
Sælger -> Webshop: Udfyld opdateret oplysninger i skemaet
Sælger -> Webshop: Klikker på gem

Webshop -> Webshop: Validerer input
alt Validering succesfuld
Webshop -> Database: Gem de nye oplysninger på forespørgsel
Database -> Webshop: Bekræft på opdatering
Webshop -> Sælger: Bekræftelse på opdatering
else Validering fejler
    Webshop -> Sælger: Fejlmeddelelse
@enduml